# Generated by Django 3.0.6 on 2020-05-23 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=36.6, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(35)])),
                ('timeStamp', models.DateTimeField(verbose_name='date-time of temperature')),
                ('active_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('FEVER', 'Fever')], default='ONGOINGFEVER', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'timeStamp')},
            },
        ),
        migrations.CreateModel(
            name='UserFeverSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='start date-time of fever session')),
                ('endTime', models.DateField(verbose_name='end date-time of fever session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'startTime')},
            },
        ),
    ]
