# Generated by Django 3.0.6 on 2020-05-24 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemps',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
