# Generated by Django 3.0.6 on 2020-05-22 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=36.6, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(35)])),
                ('timeStamp', models.DateTimeField(verbose_name='date-time of temperature')),
                ('active', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.UserProfile')),
            ],
            options={
                'unique_together': {('userId', 'timeStamp')},
            },
        ),
    ]
