# Generated by Django 3.0.6 on 2020-05-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_usertemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeverSessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(verbose_name='start date-time of fever session')),
                ('endTime', models.DateField(verbose_name='end date-time of fever session')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.UserProfile')),
            ],
        ),
    ]
