# Generated by Django 3.0.6 on 2020-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200524_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertemps',
            old_name='active_status',
            new_name='current_health',
        ),
        migrations.AddField(
            model_name='usertemps',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
