# Generated by Django 3.0.6 on 2020-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20200524_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeversessions',
            name='active_session',
            field=models.BooleanField(default=False),
        ),
    ]
