# Generated by Django 3.0.6 on 2020-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20200523_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemps',
            name='active',
        ),
        migrations.AddField(
            model_name='usertemps',
            name='active_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('FEVER', 'ONGOINGFEVER')], default='HEALTHY', max_length=8),
        ),
    ]
