# Generated by Django 3.0.6 on 2020-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20200523_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemps',
            name='active_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('FEVER', 'Fever')], default='ONGOINGFEVER', max_length=8),
        ),
    ]
