# Generated by Django 3.0.6 on 2020-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_userfeversessions_active_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeversessions',
            name='endTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
