# Generated by Django 3.0.6 on 2020-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20200524_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeversessions',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date-time of fever session'),
        ),
    ]
